#version: '3.8'							# необязательная версия yml файла 

services:							# словарь всех контенеров

  front:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    container_name: diary_frontend
    working_dir: /home/frontendapp/front/root
    command: >
      sh -c "
        python3 manage.py collectstatic --noinput &&
        python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    secrets:
      - frontend_secrets
    volumes:
      - static_volume:/home/frontendapp/front/staticfiles
    restart: unless-stopped # перезапуск контейнера при падении
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]  # --quiet - без вывода, --spider - проверка доступности без скачивания
      interval: 60s
      timeout: 30s
      start_period: 10s
      retries: 3

  bot:
    build:
      context: ./tgbot
      dockerfile: dockerfile
    container_name: diary_bot
    working_dir: /home/botapp/bot
    command: python3 main.py
    ports:
      - 8001:8000
    secrets:
      - bot_secrets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]
      interval: 60s
      timeout: 30s
      start_period: 10s
      retries: 3

  botapi:								# контейнер базы данных
    build: ./tgserver					# расположение dockerfile
    command: python3 main.py  # командна, запускаемая после запуска контенера
    ports:							# мапинг (связывание) портов
      - 8002:8000						# внешний порт:внутренний порт (на котором запущен runserver)
    secrets:
      - tgserver_secrets
      - redis_secrets
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  redis:
    image: redis:8.2.2-alpine
    container_name: tgserver_redis
    secrets:
      - redis_secrets
    volumes:
      - ./_redis/data:/data
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 16M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        source /run/secrets/redis_secrets &&
        echo "requirepass $$REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        source /run/secrets/redis_secrets &&
        if [ -n "$$REDIS_USER" ] && [ -n "$$REDIS_USER_PASSWORD" ]; then
          echo "user $$REDIS_USER on >$$REDIS_USER_PASSWORD ~* &* +@all" >> /usr/local/etc/redis/users.acl
        fi &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "sh", "-c", "source /run/secrets/redis_secrets && redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 300s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  celery_worker:
    container_name: tgserver_celery_worker
    build:
      context: ./tgserver
      dockerfile: dockerfile
    command: ["celery", '-A', 'celery_client', 'worker']
    secrets:
      - tgserver_secrets
      - redis_secrets
    depends_on:
      - redis

  celery_beat:
    container_name: tgserver_celery_beat
    build:
      context: ./tgserver
      dockerfile: dockerfile
    command: ["celery", '-A', 'celery_client', 'beat']
    secrets:
      - tgserver_secrets
      - redis_secrets
    depends_on:
      - redis

volumes:
  static_volume:

secrets:
  redis_secrets:
    file: ./_redis/redis-secrets.txt
  frontend_secrets:
    file: ./frontend/frontend-secrets.txt
  bot_secrets:
    file: ./tgbot/bot-secrets.txt
  tgserver_secrets:
    file: ./tgserver/tgserver-secrets.txt
