#version: '3.8'

services:
  front:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    container_name: diary_frontend
    working_dir: /home/frontendapp/front/root
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
        python3 manage.py collectstatic --noinput &&
        # python3 manage.py runserver 0.0.0.0:8000
        python3 -m gunicorn --config /home/frontendapp/front/gunicorn.conf.py root.wsgi:application
      "
    ports:
      - 8000:8000
    secrets:
      - frontend_secrets
    volumes:
      - static_volume:/home/frontendapp/front/root/staticfiles
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]  # --quiet - без вывода, --spider - проверка доступности без скачивания
    #   interval: 60s
    #   timeout: 30s
    #   start_period: 10s
    #   retries: 3

  authserver:
    build:
      context: ./authserver
      dockerfile: dockerfile.prod
    container_name: diary_authserver
    working_dir: /home/authserverapp/auth/root
    environment:
      - PYTHONUNBUFFERED=1
    # entrypoint: ["/home/authserverapp/auth/entrypoint.sh", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    entrypoint: ["/home/authserverapp/auth/entrypoint.sh", "python3", "-m", "gunicorn", "--config", "/home/authserverapp/auth/gunicorn.conf.py", "root.wsgi:application"]
    ports:
      - 8001:8000
    secrets:
      - authserver_secrets
    restart: unless-stopped
    depends_on:
      - auth_db
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]
    #   interval: 60s
    #   timeout: 30s
    #   start_period: 10s
    #   retries: 3

  back:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    container_name: diary_backend
    working_dir: /home/backendapp/back/root
    environment:
      - PYTHONUNBUFFERED=1
    # entrypoint: ["/home/backendapp/back/entrypoint.sh", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    entrypoint: ["/home/backendapp/back/entrypoint.sh", "python3", "-m", "gunicorn", "--config", "/home/backendapp/back/gunicorn.conf.py", "root.wsgi:application"]
    ports:
      - 8002:8000
    secrets:
      - backend_secrets
    volumes:
      - ./_media/data:/home/backendapp/back/root/mediafiles
    restart: unless-stopped
    depends_on:
      - back_db
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]
    #   interval: 60s
    #   timeout: 30s
    #   start_period: 10s
    #   retries: 3

  auth_db:
    image: postgres:16-alpine
    container_name: diary_auth_db
    secrets:
      - auth_db_secrets
    volumes:
      - ./_auth_db/data:/var/lib/postgresql/data/
    command: >
      sh -c '
        source /run/secrets/auth_db_secrets &&
        export POSTGRES_DB=$$POSTGRES_DB &&
        export POSTGRES_USER=$$POSTGRES_USER &&
        export POSTGRES_PASSWORD=$$POSTGRES_PASSWORD &&
        exec docker-entrypoint.sh postgres
      '
    # healthcheck:
    #   test: ["CMD-SHELL", "source /run/secrets/auth_db_secrets && pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped

  back_db:
    image: postgres:16-alpine
    container_name: diary_back_db
    secrets:
      - back_db_secrets
    volumes:
      - ./_back_db/data:/var/lib/postgresql/data/
    command: >
      sh -c '
        source /run/secrets/back_db_secrets &&
        export POSTGRES_DB=$$POSTGRES_DB &&
        export POSTGRES_USER=$$POSTGRES_USER &&
        export POSTGRES_PASSWORD=$$POSTGRES_PASSWORD &&
        exec docker-entrypoint.sh postgres
      '
    # healthcheck:
    #   test: ["CMD-SHELL", "source /run/secrets/back_db_secrets && pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped
  bot:
    build:
      context: ./tgbot
      dockerfile: dockerfile
    container_name: diary_bot
    working_dir: /home/botapp/bot
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py
    secrets:
      - bot_secrets
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/"]
    #   interval: 60s
    #   timeout: 30s
    #   start_period: 10s
    #   retries: 3

  botapi:
    build: ./tgserver
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 main.py
    ports:
      - 8003:8000
    secrets:
      - tgserver_secrets
      - redis_secrets
    depends_on:
      - redis
      - celery_worker
      - celery_beat

  redis:
    image: redis:8.2.2-alpine
    container_name: tgserver_redis
    secrets:
      - redis_secrets
    volumes:
      - ./_redis/data:/data
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 80M
        reservations:
          cpus: '0.1'
          memory: 16M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        source /run/secrets/redis_secrets &&
        echo "requirepass $$REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        source /run/secrets/redis_secrets &&
        if [ -n "$$REDIS_USER" ] && [ -n "$$REDIS_USER_PASSWORD" ]; then
          echo "user $$REDIS_USER on >$$REDIS_USER_PASSWORD ~* &* +@all" >> /usr/local/etc/redis/users.acl
        fi &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    # healthcheck:
    #   test: ["CMD", "sh", "-c", "source /run/secrets/redis_secrets && redis-cli -a $$REDIS_PASSWORD ping"]
    #   interval: 300s
    #   timeout: 10s
    #   retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  celery_worker:
    container_name: tgserver_celery_worker
    build:
      context: ./tgserver
      dockerfile: dockerfile
    command: ["celery", '-A', 'celery_app.celery_client', 'worker']
    environment:
      - PYTHONUNBUFFERED=1
    secrets:
      - tgserver_secrets
      - redis_secrets
    depends_on:
      - redis

  celery_beat:
    container_name: tgserver_celery_beat
    build:
      context: ./tgserver
      dockerfile: dockerfile
    command: ["celery", '-A', 'celery_app.celery_client', 'beat']
    environment:
      - PYTHONUNBUFFERED=1
    secrets:
      - tgserver_secrets
      - redis_secrets
    depends_on:
      - redis
  
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx
    ports:
      # - 1338:80
      - 80:80  # занят при локальной разработке
      - 443:443  # занят при локальной разработке
    volumes:
      - static_volume:/var/www/static
      - ./_media/data:/var/www/media
      # Для разработки (отключить в проде)
      # - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      # Для production (оба включить в проде)
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro  # :ro - read only
    depends_on:
      - front
      - authserver
      - back
    # bot и botapi nginx никак не проксирует, они общаются внутри сети docker
    # botapi делает запросы к back и authserver, но без участия браузера (а внутри сети docker)
    restart: unless-stopped

volumes:
  static_volume:

secrets:
  redis_secrets:
    file: ./_redis/redis-secrets.txt
  frontend_secrets:
    file: ./frontend/frontend-secrets.txt
  bot_secrets:
    file: ./tgbot/bot-secrets.txt
  tgserver_secrets:
    file: ./tgserver/tgserver-secrets.txt
  authserver_secrets:
    file: ./authserver/authserver-secrets.txt
  backend_secrets:
    file: ./backend/backend-secrets.txt
  auth_db_secrets:
    file: ./_auth_db/authdb-secrets.txt
  back_db_secrets:
    file: ./_back_db/backdb-secrets.txt
